Implemented atomic representation for a single element type and valence electron only representation
lcmd-epfl/Q-stack pull request #39
Opened 2024-05-02 21:40 UTC by YAY-C

- **Fix element types ordering (moved to func)**
- **Fix output name for singlet open-shell**
- **implemented single atom type rep generation**
- **Implemented valence-onyl atom density rep**
- **Fixed argument passing**
- **Refix argument-passing bug in 5653500**

2024-05-02 22:48 UTC, briling requested changes
We need tests!

2024-05-03 13:13 UTC, YAY-C commented
I added test units for the developped features within `test_spahm_a.py`.

2024-05-03 13:15 UTC, YAY-C commented
Sorry forgot to push the test-data, tests should be fine now

2024-05-03 15:06 UTC, briling reviewed
1) I don't get these lines:
```
        if valence_only:
            a_dm1[start:stop,start:stop] = 0
```

2) if in `test_water_single_element()` remove `only_z=['O']` the test still passes

2024-05-06 12:52 UTC, YAY-C commented
I explicitly check for the array `shape` within the test, that should fix the issue.

2024-05-06 18:52 UTC, briling commented
> > 2. if in `test_water_single_element()` remove `only_z=['O']` the test still passes
> 
> I explicitly check for the array `shape` within the test, that should fix the issue.

cool thanks

2024-05-06 18:52 UTC, briling commented
maybe remove the wrong valence only and have it in another pr? if we even need it

2024-05-07 08:29 UTC, YAY-C reviewed
> maybe remove the wrong valence only and have it in another pr? if we even need it

I moved all the changes for the valence stuff (now in #44),
and kept the single-element stuff in here.

I also added a few changes to get the `ecp`  parameter from the CLI `parser`.
_Should it be in a different PR?_

2024-05-07 08:33 UTC, YAY-C commented
> I also added a few changes to get the ecp parameter from the CLI parser.

 I just realized I should do the same for spahm-b, let me know if you want both in  a new PR!
 
 And I was thinking maybe in the `main()` we should enforce and warn about the need for `ecp` argument when using minao with elements heavier than Y.
_What do you think?_

2024-05-07 17:57 UTC, briling commented on qstack/spahm/rho/atom.py
maybe this
```
    for j,i in enumerate(only_i):
        q = mol.elements[i]
        v = rep[j]
```
can be replaced with this
```
    for q, v in zip(mol.elements[only_i], rep):
```
which is easier to read and more similar to the previous version

2024-05-07 18:01 UTC, briling commented
> I just realized I should do the same for spahm-b, let me know if you want both in a new PR!
> 
> And I was thinking maybe in the `main()` we should enforce and warn about the need for `ecp` argument when using minao with elements heavier than Y. _What do you think?_

yes to both! but yeah probably these ecp stuff should be separate

2024-05-07 18:01 UTC, briling requested changes

2024-05-08 15:47 UTC, YAY-C commented on qstack/spahm/rho/atom.py
I liked the one line. but it doesn't work cause `mol.elements` is a `list` and not a `numpy.array` so you can not subscript it with a list of integers.
_the intermediate option does not work neither then!_

I can create a copy of `mol.elements` in a `numpy.array` and go for the oneliner, but it feels a bit like an overhead.
_what do you think?_

2024-05-08 16:20 UTC, YAY-C reviewed
- feels like less trouble to leave it like this:
```
    for j,i in enumerate(only_i):
        q = mol.elements[i]
        v = rep[j]
```
- and I moved the ECP changes to a new issue/branch #48

2024-05-08 18:09 UTC, briling commented on qstack/spahm/rho/atom.py
i'd put `zip(np.array(mol.elements)[only_i], rep)]` lol

2024-05-08 18:13 UTC, briling commented
at this point there's so many commits and reverts that I'd squash and merge rather than merge

2024-05-08 18:14 UTC, briling commented on qstack/spahm/rho/atom.py
I just don't like j,i

2024-05-09 20:33 UTC, YAY-C reviewed
sinlge-line code

2024-05-09 20:33 UTC, YAY-C commented on qstack/spahm/rho/atom.py
ahah sure! Done 👌

2024-05-09 20:35 UTC, YAY-C commented
> at this point there's so many commits and reverts that I'd squash and merge rather than merge

agreed, "17 commits" sounds too much for so few changes in the end!

I have never done it though, you wan to do it?

2024-05-09 20:59 UTC, merged