Fix #48 add ecp arguments to main function and cli parser
lcmd-epfl/Q-stack pull request #49
Opened 2024-05-09 22:02 UTC by YAY-C

- **Add ECP argument to CLI**
- **Add check to set ecp when necessary with 'minao' basis**
- **Added ecp argument to CLI parser and check for minao basis**

2024-05-10 13:56 UTC, briling requested changes

2024-05-10 13:56 UTC, briling commented on qstack/spahm/rho/bond.py
> +    import pyscf.data.elements as pysymb
* I don't think it's good to forcely set ecp. Better raise an error
* This checking code should be a separate function in `compound.py`, if not inside of `xyz_to_mol`

2024-05-13 08:55 UTC, YAY-C commented
Should we make a test for `xyz_to_mol()` (397b2f4)?

_if yes, would the test `assert()` the `RuntimeError` raising?_

2024-05-13 10:13 UTC, briling commented
> Should we make a test for `xyz_to_mol()` ([397b2f4](https://github.com/lcmd-epfl/Q-stack/commit/397b2f48b4ddb6108497cf989f3e98c593f8815f))?
> 
> _if yes, would the test `assert()` the `RuntimeError` raising?_

There's a test in `test_compound.py` but it doesn't really do anything. Can be updated in another batch of changes

2024-05-13 10:19 UTC, briling requested changes

2024-05-13 10:19 UTC, briling commented on qstack/compound.py
> +    if ecp != None:
I think `is not None`/`is None` (below) is more clean

2024-05-13 10:19 UTC, briling commented on qstack/compound.py
> +    if mol.basis == 'minao' and ecp == None and (np.array(species_charges) > 39).any():
minao needs ecp for Y (hence `>=39`) but I think it should be `>36` (after Kr)

2024-05-13 12:21 UTC, YAY-C reviewed
- for the `is None`/`is not None`
I checked and there are a few of those in other files (not concerned by this PR `kernel_utils.py`, `hyperparameters.py`, `rep_completion.py`).
Maybe it's better to make this changes in another batch.
_I still have two PR with different changes to request and one of them includes changes in theses files!_

2024-05-13 14:14 UTC, briling commented
Okay let's fix is/== None another time!

2024-05-13 14:15 UTC, briling requested changes

2024-05-13 14:15 UTC, briling commented on qstack/compound.py
>          msg = f"{mol.basis} basis set requires the use of effective core potentials for atoms with Z>39"
also here! sorry

2024-05-13 18:15 UTC, merged